### ISSUE TITLE
Make  Error After install jansson

### ISSUE THREAD

**Issue by portgasray** [yzfedora/baidudl#15]
according to the error information, I installed jasson-2.12 successfully, but when I make again, another make error occured
Here is my error detail:
```
/usr/local/include/jansson.h:135: undefined reference to `json_delete'
collect2: error: ld returned 1 exit status
Makefile:345: recipe for target 'bdpandl' failed
make[2]: *** [bdpandl] Error 1
make[2]: Leaving directory '/home/lei/github-repo/baidudl/src'
Makefile:351: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lei/github-repo/baidudl'
Makefile:292: recipe for target 'all' failed
make: *** [all] Error 2
```
happened at:  `Ubuntu 18.04 amd64`

**Comment by yzfedora** [comment]
Maybe the jansson library you installed has some problem. the source code never call the `json_delete()` function. I am using the Fedora, here is the jansson library that I installed.

$ rpm -qa | grep jansson
jansson-devel-doc-2.10-4.fc27.noarch
jansson-2.10-4.fc27.x86_64
jansson-devel-2.10-4.fc27.x86_64
jansson-debuginfo-2.9-1.fc25.x86_64

also, you need make sure there is no any error when you run `./autogen.sh`.

**Comment by barf** [comment]
also unable to build with libjansson-dev 2.12-1build1 on Ubuntu

**Comment by yzfedora** [comment]
Try locate the libjansson library file first.
```
find /usr -name "libjansson*so*"
```

If the libjansson is installed under a non-standard folder, you may need add the path of that folder to `/etc/ld.so.conf`.  run `ldconfig` command and try compile it again.

**Comment by barf** [comment]
That does not fix it. It's installed in standard location, and available in the library search path. I can build the jansson examples OK. I think the configure script/Makefile is not including it correctly.
```
$ make
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT bdpandl.o -MD -MP -MF .deps/bdpandl.Tpo -c -o bdpandl.o bdpandl.c
mv -f .deps/bdpandl.Tpo .deps/bdpandl.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlcommon.o -MD -MP -MF .deps/dlcommon.Tpo -c -o dlcommon.o dlcommon.c
mv -f .deps/dlcommon.Tpo .deps/dlcommon.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlinfo.o -MD -MP -MF .deps/dlinfo.Tpo -c -o dlinfo.o dlinfo.c
mv -f .deps/dlinfo.Tpo .deps/dlinfo.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlpart.o -MD -MP -MF .deps/dlpart.Tpo -c -o dlpart.o dlpart.c
mv -f .deps/dlpart.Tpo .deps/dlpart.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlscrolling.o -MD -MP -MF .deps/dlscrolling.Tpo -c -o dlscrolling.o dlscrolling.c
dlscrolling.c: In function ‘dlscrolling_ptr’:
dlscrolling.c:113:15: warning: ‘t’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  113 |  unsigned int t;
      |               ^
mv -f .deps/dlscrolling.Tpo .deps/dlscrolling.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dllist.o -MD -MP -MF .deps/dllist.Tpo -c -o dllist.o dllist.c
mv -f .deps/dllist.Tpo .deps/dllist.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT err_handler.o -MD -MP -MF .deps/err_handler.Tpo -c -o err_handler.o err_handler.c
err_handler.c: In function ‘err_internal’:
err_handler.c:237:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  237 |   write(STDERR_FILENO, buf, len);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/err_handler.Tpo .deps/err_handler.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlbuffer.o -MD -MP -MF .deps/dlbuffer.Tpo -c -o dlbuffer.o dlbuffer.c
mv -f .deps/dlbuffer.Tpo .deps/dlbuffer.Po
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O2 -g -MT dlssl.o -MD -MP -MF .deps/dlssl.Tpo -c -o dlssl.o dlssl.c
mv -f .deps/dlssl.Tpo .deps/dlssl.Po
gcc  -Wall -O2 -g -Wall -Wextra -lpthread -ljansson  -o bdpandl bdpandl.o dlcommon.o dlinfo.o dlpart.o dlscrolling.o dllist.o err_handler.o dlbuffer.o dlssl.o  -lcurl -lpthread 
/usr/bin/ld: dlpart.o: in function `baidu_error_check':
/home/barf/baidudl/src/dlpart.c:46: undefined reference to `json_loadb'
/usr/bin/ld: /home/barf/baidudl/src/dlpart.c:49: undefined reference to `json_object_get'
/usr/bin/ld: /home/barf/baidudl/src/dlpart.c:50: undefined reference to `json_object_get'
/usr/bin/ld: /home/barf/baidudl/src/dlpart.c:54: undefined reference to `json_integer_value'
/usr/bin/ld: /home/barf/baidudl/src/dlpart.c:55: undefined reference to `json_string_value'
/usr/bin/ld: dlpart.o: in function `json_decref':
/usr/local/include/jansson.h:133: undefined reference to `json_delete'
/usr/bin/ld: /usr/local/include/jansson.h:133: undefined reference to `json_delete'
collect2: error: ld returned 1 exit status
make: *** [Makefile:352: bdpandl] Error 1
```

**Comment by eugenelee0420** [comment]
Encountered the same error on Ubuntu 19.10:
```
$ make
make  all-recursive
make[1]: Entering directory '/home/eugene/Desktop/baidudl'
Making all in src
make[2]: Entering directory '/home/eugene/Desktop/baidudl/src'
gcc  -Wall -O2 -g -Wall -Wextra -lpthread -ljansson  -o bdpandl bdpandl.o dlcommon.o dlinfo.o dlpart.o dlscrolling.o dllist.o err_handler.o dlbuffer.o dlssl.o  -lcurl -lpthread
/usr/bin/ld: dlpart.o: in function `baidu_error_check':
/home/eugene/Desktop/baidudl/src/dlpart.c:46: undefined reference to `json_loadb'
/usr/bin/ld: /home/eugene/Desktop/baidudl/src/dlpart.c:49: undefined reference to `json_object_get'
/usr/bin/ld: /home/eugene/Desktop/baidudl/src/dlpart.c:50: undefined reference to `json_object_get'
/usr/bin/ld: /home/eugene/Desktop/baidudl/src/dlpart.c:54: undefined reference to `json_integer_value'
/usr/bin/ld: /home/eugene/Desktop/baidudl/src/dlpart.c:55: undefined reference to `json_string_value'
/usr/bin/ld: dlpart.o: in function `json_decref':
/usr/include/jansson.h:135: undefined reference to `json_delete'
/usr/bin/ld: /usr/include/jansson.h:135: undefined reference to `json_delete'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:352: bdpandl] Error 1
make[2]: Leaving directory '/home/eugene/Desktop/baidudl/src'
make[1]: *** [Makefile:351: all-recursive] Error 1
make[1]: Leaving directory '/home/eugene/Desktop/baidudl'
make: *** [Makefile:292: all] Error 2
```

Fixed by appending`-ljansson` to the `LIBS =` line in the Makefile so that `-ljansson` is at the end of the gcc command.
```
LIBS = -lcurl -lpthread -ljansson
```

**Comment by portgasray** [comment]
Just use the [Install](https://github.com/yzfedora/baidudl#install) here, already works for me, but I cannot download a share link.
```
$ sudo dpkg -i baidudl_1.0-1_amd64.deb
dpkg: warning: files list file for package 'libeigen3-dev' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'opencv-data' missing; assuming package has no files currently installed
(Reading database ... 458969 files and directories currently installed.)
Preparing to unpack baidudl_1.0-1_amd64.deb ...
Unpacking baidudl (1.0-1) over (1.0-1) ...
Setting up baidudl (1.0-1) ...
```
